/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FreshRouteImport } from './routes/fresh'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MixRouteImport } from './routes/mix'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshRoute = FreshRouteImport.update({
  id: '/fresh',
  path: '/fresh',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/fresh': typeof FreshRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mix': typeof MixRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/p/$id': typeof PIdRoute
  '/t/$id': typeof TIdRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/fresh': typeof FreshRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mix': typeof MixRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/p/$id': typeof PIdRoute
  '/t/$id': typeof TIdRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/fresh': typeof FreshRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mix': typeof MixRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/p/$id': typeof PIdRoute
  '/t/$id': typeof TIdRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/discover'
    | '/explore'
    | '/fresh'
    | '/friends'
    | '/library'
    | '/login'
    | '/mix'
    | '/radio'
    | '/search'
    | '/settings'
    | '/stats'
    | '/api/proxy'
    | '/p/$id'
    | '/t/$id'
    | '/u/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/discover'
    | '/explore'
    | '/fresh'
    | '/friends'
    | '/library'
    | '/login'
    | '/mix'
    | '/radio'
    | '/search'
    | '/settings'
    | '/stats'
    | '/api/proxy'
    | '/p/$id'
    | '/t/$id'
    | '/u/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/discover'
    | '/explore'
    | '/fresh'
    | '/friends'
    | '/library'
    | '/login'
    | '/mix'
    | '/radio'
    | '/search'
    | '/settings'
    | '/stats'
    | '/api/proxy'
    | '/p/$id'
    | '/t/$id'
    | '/u/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  FreshRoute: typeof FreshRoute
  FriendsRoute: typeof FriendsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MixRoute: typeof MixRoute
  RadioRoute: typeof RadioRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  ApiProxyRoute: typeof ApiProxyRoute
  PIdRoute: typeof PIdRoute
  TIdRoute: typeof TIdRoute
  UIdRoute: typeof UIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh': {
      id: '/fresh'
      path: '/fresh'
      fullPath: '/fresh'
      preLoaderRoute: typeof FreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  FreshRoute: FreshRoute,
  FriendsRoute: FriendsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MixRoute: MixRoute,
  RadioRoute: RadioRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  ApiProxyRoute: ApiProxyRoute,
  PIdRoute: PIdRoute,
  TIdRoute: TIdRoute,
  UIdRoute: UIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
